const lines=[
{game:'VALORANT',badge:'V',player:'aspas',teams:'MIBR vs. Sentinels',market:'Kills · Maps 1–2',line:35.5,projection:40.1,side:'Over',edge:13,confidence:89,startAt:'2026-09-01T19:00:00Z',h2h:'3/4',values:[42,39,34,44,41,37,47,32,40,45],opponent:'Sentinels'},
{game:'CS2',badge:'CS',player:'donk',teams:'Spirit vs. FaZe',market:'Kills · Map 1',line:18.5,projection:21,side:'Over',edge:13.5,confidence:87,startAt:'2026-09-01T20:30:00Z',h2h:'4/5',values:[23,20,18,25,21,19,24,17,22,20],opponent:'FaZe'},
{game:'League of Legends',badge:'LoL',player:'Chovy',teams:'Gen.G vs. T1',market:'Kills · Series',line:10.5,projection:12,side:'Over',edge:12.7,confidence:84,startAt:'2026-09-01T22:00:00Z',h2h:'5/7',values:[13,9,12,15,11,14,10,16,13,12],opponent:'T1'},
{game:'VALORANT',badge:'V',player:'Derke',teams:'FNATIC vs. BBL',market:'Kills · Maps 1–2',line:35.5,projection:39.1,side:'Over',edge:10.1,confidence:81,startAt:'2026-09-01T17:00:00Z',h2h:'2/3',values:[40,34,31,42,37,35,44,29,39,36],opponent:'BBL'},
{game:'CS2',badge:'CS',player:'ZywOo',teams:'Vitality vs. NAVI',market:'Kills · Maps 1–2',line:36.5,projection:40.2,side:'Over',edge:10.1,confidence:79,startAt:'2026-09-01T23:00:00Z',h2h:'6/9',values:[42,37,41,33,45,38,36,43,39,40],opponent:'NAVI'},
{game:'League of Legends',badge:'LoL',player:'Gumayusi',teams:'T1 vs. Gen.G',market:'Kills · Series',line:10.5,projection:11.4,side:'Over',edge:8.7,confidence:72,startAt:'2026-09-01T22:00:00Z',h2h:'4/7',values:[12,10,11,9,13,12,10,14,11,12],opponent:'Gen.G'},
{game:'VALORANT',badge:'V',player:'t3xture',teams:'G2 vs. Paper Rex',market:'Kills · Map 1',line:17.5,projection:18.9,side:'Over',edge:8,confidence:71,startAt:'2026-09-02T01:30:00Z',h2h:'1/2',values:[19,22,15,18,21,17,20,16,19,23],opponent:'Paper Rex'},
{game:'CS2',badge:'CS',player:'m0NESY',teams:'G2 vs. Falcons',market:'Kills · Map 1',line:18.5,projection:17.1,side:'Under',edge:7.6,confidence:68,startAt:'2026-09-02T02:00:00Z',h2h:'2/4',values:[17,16,18,15,14,17,16,19,15,17],opponent:'Falcons'}];
lines.push(
);
// These rows demonstrate the research UI only. They are never a claim that a player is confirmed to start today.
lines.forEach(x=>x.source='Test-drive research — schedule/roster verification pending');
let game='All',query='',sort='edge',side='All',windowSize='5';const watched=new Set(JSON.parse(localStorage.getItem('pulse-watchlist')||'[]')),iconClass=n=>n==='VALORANT'?'valorant':n==='CS2'?'cs2':'lol';
const localTime=utc=>new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(utc));lines.forEach(x=>x.time=localTime(x.startAt));
const rate=(x,n)=>{let a=x.values.slice(-(n==='h2h'?5:+n));return a.filter(v=>x.side==='Over'?v>x.line:v<x.line).length+'/'+a.length};
function render(){let v=lines.filter(x=>(game==='All'||x.game===game)&&(side==='All'||x.side===side)&&`${x.player} ${x.teams}`.toLowerCase().includes(query));v.sort((a,b)=>sort==='edge'?b.edge-a.edge:sort==='confidence'?b.confidence-a.confidence:new Date(a.startAt)-new Date(b.startAt));linesList.innerHTML=v.map(x=>`<article class="line-row" data-player="${x.player}"><div class="player"><span class="game-icon ${iconClass(x.game)}">${x.badge}</span><div><strong>${x.player}</strong><small>${x.teams} · ${localTime(x.startAt)} · Test drive</small></div></div><div class="market">${x.market}</div><div class="line">${x.side==='Over'?'O':'U'} ${x.line}</div><div class="form ${x.side==='Under'?'under':''}">${x.side} ${rate(x,windowSize)}</div><div class="h2h">${x.h2h} vs opp.</div><div class="projection"><b>${x.projection}</b><small>+${x.edge}%</small></div><button class="watch ${watched.has(x.player)?'saved':''}" data-player="${x.player}">${watched.has(x.player)?'★':'☆'}</button></article>`).join('');empty.textContent=game==='Dota 2'?'No verified Dota kills lines yet. The real OpenDota pro directory is below.':'No kills lines match those filters.';empty.classList.toggle('hidden',v.length>0);watchCount.textContent=watched.size;watchHero.innerHTML=`${watched.size} <span>saved</span>`}
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2000)}const toastEl=document.querySelector('#toast'),linesList=document.querySelector('#linesList'),empty=document.querySelector('#empty'),watchCount=document.querySelector('#watchCount'),watchHero=document.querySelector('#watchHero');
function drawer(x){let vals=x.values.slice(-5),avg=(vals.reduce((a,b)=>a+b,0)/5).toFixed(1),hits=vals.filter(v=>x.side==='Over'?v>x.line:v<x.line).length;drawerContent.innerHTML=`<div class="drawer-title"><span class="game-icon ${iconClass(x.game)}">${x.badge}</span><div><h2>${x.player}</h2><p>${x.teams} · ${x.time}</p></div></div><div class="prop-summary"><div><strong>${x.market}</strong><small>${x.source}</small></div><div class="choice-group"><button class="choice active ${x.side.toLowerCase()}">${x.side} ${x.line}</button><button class="choice">${x.side==='Over'?'Under':'Over'} ${x.line}</button></div></div><div class="detail-tabs"><button class="active">Performance</button><button>Matchup</button><button>Market</button></div><div class="stats-grid"><div class="stat"><span>L5 AVG</span><b>${avg}</b></div><div class="stat"><span>L5 ${x.side}</span><b>${hits}/5</b></div><div class="stat"><span>L10 ${x.side}</span><b>${rate(x,'10')}</b></div><div class="stat"><span>L20 ${x.side}</span><b>${rate(x,'20')}</b></div><div class="stat"><span>H2H</span><b>${x.h2h}</b></div></div><div class="chart-card"><div class="card-title"><h3>Last 10 games</h3><small>Line: ${x.line}</small></div><div class="bars">${x.values.map(v=>`<div class="bar-col" data-value="${v}"><i class="bar ${(x.side==='Over'?v>x.line:v<x.line)?'hit':'miss'}" style="height:${Math.max(12,v/Math.max(...x.values)*100)}%"></i></div>`).join('')}</div><div class="game-labels"><span>10 ago</span><span>Recent</span></div></div><div class="insight-card"><div class="card-title"><h3>Matchup context</h3><small>${x.opponent}</small></div><div class="splits"><div class="split">vs. ${x.opponent}<b>${x.h2h}</b></div><div class="split">Projected pace<b>+7%</b></div><div class="split">Map pool rank<b>Top 5</b></div><div class="split">Rest days<b>2</b></div></div></div><div class="chart-card"><div class="card-title"><h3>Line movement</h3><small>Sample movement ${x.line-1} → ${x.line}</small></div><svg class="movement" viewBox="0 0 440 90" preserveAspectRatio="none"><path d="M0 66 L48 60 L92 62 L136 47 L181 50 L225 36 L270 41 L315 27 L365 31 L440 17" fill="none" stroke="#7856f2" stroke-width="3"/><path d="M0 90 L0 66 L48 60 L92 62 L136 47 L181 50 L225 36 L270 41 L315 27 L365 31 L440 17 L440 90" fill="#7856f210"/></svg></div><div class="book-card"><div class="card-title"><h3>Market comparison</h3><small>Sample lines</small></div><div class="book-row"><span>Atlas</span><strong>O ${x.line} · -110</strong><i class="best">BEST</i></div><div class="book-row"><span>Prime</span><strong>O ${x.line} · -118</strong></div><div class="book-row"><span>Northstar</span><strong>O ${x.line+.5} · -112</strong></div></div>`;drawerEl.classList.add('open')}
const drawerEl=document.querySelector('#drawer'),drawerContent=document.querySelector('#drawerContent');drawerContent.addEventListener('click',event=>{const choice=event.target.closest('.choice');if(!choice)return;const group=choice.closest('.choice-group');group.querySelectorAll('.choice').forEach(button=>button.classList.toggle('active',button===choice));const sideLabel=choice.textContent.trim().split(' ')[0];toast(`${sideLabel} selected for this kills line`)});document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{game=t.dataset.game;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));render()});document.querySelectorAll('#sideFilter button').forEach(t=>t.onclick=()=>{side=t.dataset.side;document.querySelectorAll('#sideFilter button').forEach(x=>x.classList.toggle('selected',x===t));render()});document.querySelectorAll('.window').forEach(t=>t.onclick=()=>{windowSize=t.dataset.window;document.querySelectorAll('.window').forEach(x=>x.classList.toggle('active',x===t));render()});document.querySelector('#search').oninput=e=>{query=e.target.value.toLowerCase();render()};document.querySelector('#sort').onchange=e=>{sort=e.target.value;render()};linesList.onclick=e=>{let b=e.target.closest('.watch');if(b){let p=b.dataset.player;watched.has(p)?watched.delete(p):watched.add(p);localStorage.setItem('pulse-watchlist',JSON.stringify([...watched]));toast(watched.has(p)?`${p} added to watchlist`:`${p} removed`);render();return}let r=e.target.closest('.line-row');if(r)drawer(lines.find(x=>x.player===r.dataset.player))};document.querySelectorAll('#closeDrawer,#closeDrawerButton').forEach(e=>e.onclick=()=>drawerEl.classList.remove('open'));document.querySelector('#clearWatch').onclick=()=>{watched.clear();localStorage.setItem('pulse-watchlist',JSON.stringify([...watched]));render();toast('Watchlist cleared')};document.querySelector('#themeButton').onclick=()=>document.body.classList.toggle('dark');document.querySelector('#refreshButton').onclick=()=>{render();toast('Lines are up to date')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
