(() => {
  const table=document.querySelector('#rows');if(!table)return;
  const controls=document.createElement('section');controls.className='prop-filter-controls';controls.setAttribute('aria-label','Filter PrizePicks props');
  controls.innerHTML='<label>Map range<select data-map><option value="">All maps</option><option value="1-2">Maps 1–2</option><option value="1-3">Maps 1–3</option></select></label><label>Market<select data-type><option value="">Players & combos</option><option value="single">Individual players</option><option value="combo">Combos</option></select></label><label>Line type<select data-variant><option value="">All line types</option><option value="standard">Standard</option><option value="demon">Demon</option><option value="goblin">Goblin</option></select></label><button type="button">Reset filters</button><p role="status"></p>';
  table.before(controls);
  const style=document.createElement('style');style.textContent='.prop-filter-controls{display:flex;flex-wrap:wrap;gap:12px;align-items:end;margin:14px 0}.prop-filter-controls label{font-size:14px;font-weight:750;color:#c4d7de;flex:1;min-width:150px}.prop-filter-controls select{display:block;width:100%;margin-top:5px;padding:11px;color:#f1f5f8;background:#102538;border:1px solid #718b9c;border-radius:8px;font-size:16px}.prop-filter-controls button{padding:12px;min-height:44px;background:#193448;color:#f0d690;border:1px solid #d4b76566;border-radius:8px;cursor:pointer}.prop-filter-controls p{width:100%;margin:0;font-size:14px;color:#b3cbd0}.row[hidden]{display:none!important}@media(max-width:760px){.row .market{display:block!important;grid-column:1/-1}.prop-filter-controls label{min-width:130px}.prop-filter-controls{gap:8px}}';document.head.append(style);
  function apply(){const map=controls.querySelector('[data-map]').value,type=controls.querySelector('[data-type]').value,variant=controls.querySelector('[data-variant]').value;let count=0;const rows=table.querySelectorAll('.row');rows.forEach(row=>{const market=row.querySelector('.market')?.textContent.toLowerCase().replaceAll('–','-')||'',combo=market.includes('combo');row.hidden=Boolean((map&&!market.includes(map))||(type==='combo'&&!combo)||(type==='single'&&combo)||(variant&&!market.includes(variant)));if(!row.hidden)count++;});controls.querySelector('[role=status]').textContent=`${count} of ${rows.length} matching props`;}
  controls.onchange=apply;controls.querySelector('button').onclick=()=>{controls.querySelectorAll('select').forEach(select=>select.value='');apply();};new MutationObserver(apply).observe(table,{childList:true});apply();
})();
