(() => {
  const teams = [
    { team:'Barça Esports', event:'LES Playoffs', source:'FC Barcelona official 2026 roster', players:[['Selenex','Top','Confirmed starter'],['Koldo','Jungle','Confirmed starter'],['Macaquiño','Mid','Confirmed starter'],['Legolas','ADC','Confirmed starter'],['Oscure','Support','Confirmed starter']] },
    { team:'UCAM Esports Club', event:'LES Playoffs', source:'Current roster listing · starter check pending', players:[['Fresskowy','Role pending','Rostered'],['Time','Role pending','Rostered'],['NightSlayer','Role pending','Rostered'],['113','Role pending','Rostered'],['Bluerzor','Role pending','Rostered'],['ESCIK','Role pending','Rostered'],['iLevi','Role pending','Rostered'],['Andariel','Role pending','Rostered'],['Kozi','Role pending','Rostered'],['Myrtus','Role pending','Rostered]] },
    { team:'MIBR', event:'IEM Beijing 2026 Closed Qualifier', source:'Upcoming match lineup', players:[['tomaszin','CS2','Confirmed starter'],['insani','CS2','Confirmed starter'],['nqz','CS2','Confirmed starter'],['venomzera','CS2','Confirmed starter'],['LNZ','CS2','Confirmed starter']] },
    { team:'Eternal Fire', event:'IEM Beijing 2026 Closed Qualifier', source:'Upcoming match lineup', players:[['soulfly','CS2','Confirmed starter'],['regali','CS2','Confirmed starter'],['Kvem','CS2','Confirmed starter'],['jottAAA','CS2','Confirmed starter'],['MisteM','CS2','Confirmed starter']] },
    { team:'3DMAX', event:'IEM Beijing 2026 Closed Qualifier', source:'Upcoming match lineup', players:[['Maka','CS2','Confirmed starter'],['Lucky','CS2','Confirmed starter'],['Graviti','CS2','Confirmed starter'],['misutaaa','CS2','Confirmed starter'],['Kursy','CS2','Confirmed starter']] },
    { team:'HEROIC', event:'IEM Beijing 2026 Closed Qualifier', source:'Upcoming match lineup', players:[['Brollan','CS2','Confirmed starter'],['MartinezSa','CS2','Confirmed starter'],['nilo','CS2','Confirmed starter'],['Chr1zN','CS2','Confirmed starter'],['susp','CS2','Confirmed starter]] },
  ];
  document.querySelector('#rosterBoard').innerHTML = teams.map(team => `<article class="roster-card"><h2>${team.team}</h2><p>${team.event} · ${team.source}</p>${team.players.map(([name, role, status]) => `<div class="member"><span><strong>${name}</strong><br><small>${role}</small></span><b class="${status === 'Confirmed starter' ? 'status-start' : 'status-roster'}">${status}</b></div>`).join('')}</article>`).join('');
})();
