(() => {
  // Factual schedule snapshot collected from the current public match calendars.
  // The production server will replace this with an authorized, automatically refreshed feed.
  const fixtures = [
    { game:'CS2', event:'ESL Challenger League Season 52 NA Cup 1 · Grand Final', teams:'Voca vs Marsborne', time:'Live now', source:'HLTV schedule snapshot', status:'LIVE' },
    { game:'VALORANT', event:'THE POKAL 2026 · Upper Round of 16', teams:'Catboys vs SGE & Friends', time:'4:00 PM', source:'VLR schedule snapshot', status:'LIVE' },
    { game:'VALORANT', event:'Source League 2026 · Summer Split Lower Final', teams:'Abstract vs INPUTLAG', time:'5:30 PM', source:'VLR schedule snapshot', status:'LIVE' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Upper Quarterfinal', teams:'FlyQuest RED vs MVSK Secret', time:'10:00 PM', source:'VLR schedule snapshot', status:'LIVE' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Upper Quarterfinal', teams:'The Spiders vs Axolotl', time:'10:00 PM', source:'VLR schedule snapshot', status:'LIVE' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'MIBR vs Eternal Fire', time:'11:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Asia Closed Qualifier', teams:'TYLOO vs Kaleido', time:'08:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Asia Closed Qualifier', teams:'The Huns vs DEPO', time:'08:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Asia Closed Qualifier', teams:'FlyQuest vs NEXVOID', time:'08:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Asia Closed Qualifier', teams:'Rare Atom vs Lynn Vision', time:'08:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'Logitech G Play Connect 2026 Closed Qualifier', teams:'SINNERS vs EAC', time:'10:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'3DMAX vs HEROIC', time:'11:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'FISSURE Playground 3 Asia Closed Qualifier', teams:'The Huns vs Chinggis Warriors', time:'11:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'NODWIN Clutch Series 11 · Quarterfinal', teams:'Nemesis vs 1win', time:'13:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'BIG vs Nemiga', time:'14:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'HOTU vs paiN', time:'14:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'magic vs K27', time:'11:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'Nuclear TigeRES vs GamerLegion', time:'11:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'IEM Beijing 2026 Closed Qualifier', teams:'DENDELE vs EYEBALLERS', time:'14:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'FISSURE Playground 3 Asia Closed Qualifier', teams:'Rare Atom vs 5star', time:'14:30', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'NODWIN Clutch Series 11 · Quarterfinal', teams:'Black Phoenix vs INFINITE', time:'16:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'Logitech G Play Connect 2026 Closed Qualifier', teams:'Walczaki vs Metizport', time:'16:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'CCT 2026 Europe Series 8', teams:'INOX Division vs UNiTY', time:'16:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'CCT 2026 South America Series 5', teams:'Grêmio vs MEIA NOITE', time:'18:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'NODWIN Clutch Series 11 · Quarterfinal', teams:'3DMAX vs Walczaki', time:'19:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'Logitech G Play Connect 2026 Closed Qualifier', teams:'Iberian Soul vs 9INE', time:'19:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'CCT 2026 Europe Series 8', teams:'EAC vs Bushido Wildcats', time:'19:00', source:'HLTV schedule snapshot' },
    { game:'CS2', event:'CCT 2026 South America Series 5', teams:'BESTIA Academy vs DAMAJUANA', time:'21:00', source:'HLTV schedule snapshot' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Upper Semifinal', teams:'FlyQuest RED vs Axolotl', time:'Upcoming', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Lower Round 1', teams:'MVSK vs The Spiders', time:'Upcoming', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Upper Semifinal', teams:'SwimTrek Blue vs Shopify Rebellion Gold', time:'Upcoming', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Game Changers 2026 · NA Stage 2 · Lower Round 1', teams:'Cloud9 GC vs HIMMERS', time:'Upcoming', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Noob Esports vs Arcade Esports', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:"Sanctuary vs Dil's Pickles", time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Solarex vs GANGA', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Error 404 vs Crusaders', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'TROOPERS vs Evolve', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Whaler Gaming NX vs QUT RESPAWN', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'MeatZn vs Balkan Tuah', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Trident Esports vs china project x', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'PACIFIC REIGN vs NORTHBOUND', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Waterfall vs Prime ASD', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'Celestial vs NS Overtime', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:'PupilsOfTheGame vs Disproportion', time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'Wave OCE 2026 · Breakwater Open', teams:"Sel's Warriors vs Tickle Monsters", time:'10:00 AM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'THE POKAL 2026 · Upper Quarterfinal', teams:'BERG vs GamerZ Esports', time:'4:00 PM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'THE POKAL 2026 · Upper Quarterfinal', teams:'Glacial Guardians vs CGN Esports', time:'4:00 PM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'THE POKAL 2026 · Lower Round 1', teams:'ALTERNATE aTTaX Ruby vs Sissi State Punks', time:'4:00 PM', source:'VLR schedule snapshot' },
    { game:'VALORANT', event:'THE POKAL 2026 · Lower Round 1', teams:'RIZON Sugar vs HooK Esport', time:'4:00 PM', source:'VLR schedule snapshot' },
  ];
  const board = document.querySelector('#scheduleBoard');
  const groups = fixtures.reduce((all, fixture) => ((all[fixture.game] ||= []).push(fixture), all), {});
  board.innerHTML = Object.entries(groups).map(([game, list]) => `<section class="schedule-day"><h2>${game} <small>(${list.length})</small>${game === 'Dota 2' ? '' : ''}</h2>${list.map(fixture => `<article class="fixture"><small>${fixture.time}</small><div><b>${fixture.teams}</b><small>${fixture.event} · ${fixture.source}</small></div><span class="fixture-status">${fixture.status || 'UPCOMING'}</span></article>`).join('')}</section>`).join('');
  document.querySelector('#fixtureCount').innerHTML = `${fixtures.length} <span>fixtures</span>`;
})();
